### ISSUE TITLE
ERROR invalid javascript property identifier character

### ISSUE THREAD

**Issue by Bigpapa114** [JustEmuTarkov/JET-ProfileEditor#6]
whenever i Run the profile editor it gives me invalid javascript property identifier character, Any solution to this
![Screenshot (9)](https://user-images.githubusercontent.com/83498667/116780748-193d4d00-aa9c-11eb-9363-aa7a6ffc218b.png)

**Comment by kura1337** [comment]
did you fix it ?

**Comment by Tanishq1tanishq** [comment]
i have the same problem

**Comment by Bigpapa114** [comment]
> did you fix it ?

No Not yeh cant find any

**Comment by thumpnail** [comment]
properly trying to read an invalid js char. so in one json file is a char which is "not valid".

**Comment by kiobu** [comment]
This is a syntax error in your character.json file from an edit you made, has nothing to do with the profile editor.

Run the file through a JSON validator and fix the syntax error before attempting to use the profile editor.

**Comment by thumpnail** [comment]
Sorry to say this but my Character.json file IS valid, otherwise i couldnt use the profile since it is not valid.
![image](https://user-images.githubusercontent.com/31255152/134471344-b80528bd-d363-490e-8568-0fa3e0db3b05.png)
